---
- name: Clone a private repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ repo_path }}"
    version: "{{ repo_branch }}"
    accept_hostkey: yes
#    clone: yes

- name: Retrieve an authentication token and authenticate Docker client
  shell: 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 489194400276.dkr.ecr.us-east-1.amazonaws.com'

#- name: Build docker image
#  docker_image: 
#    path: "{{ repo_path }}"
#    name: "{{ image_name }}"
#    tag: "{{ image_version }}"

- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: "{{ repo_path }}"
    name: "{{ ecr_repositoryUri }}/{{ image_name }}"
    tag: "{{ image_version }}"
    push: yes
    source: build