---
- name: Add NodeSource yum repository
  shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -'

- name: Installing "{{ packages }}"
  yum:
    name:  "{{ packages }}"
    state: latest

- name: Clone a private repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ repo_path }}"
    version: "{{ repo_branch }}"
    accept_hostkey: yes
#    clone: yes

- name: Install packages based on package.json using the npm
  npm:
    path: "{{ repo_path }}"
    state: present  
      
- name: Build app
  command: npm run build
  args:
    chdir: "{{ repo_path }}"